# Qualtrics Data Cleaning
Raw survey data exported from Qualtrics is cleaned and prepared for analysis. This includes column renaming, device type mapping, consolidating phone pickup data across device types, calculating average daily pickups, and merging with PsychoPy inhibition scores. The output is a single analysis-ready CSV containing all variables needed for the main correlation analysis.

In [2]:
import pandas as pd
import os

In [3]:
OUTPUT_FOLDER_PATH = "/Users/remyfernando/Desktop/Noguchi Active/BSc Psychology/Year 3/Research Project/Project data"

In [4]:
file_path =  "/Users/remyfernando/Desktop/Noguchi Active/BSc Psychology/Year 3/Research Project/Project data/Qualtrics_raw_original.csv"
df = pd.read_csv(file_path)
df.head()

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,A.M,A.T,A.W,A.Th,A.F,A.S,A.Su,IOS pick-ups,Q62,MAAS average
0,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,...,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,6. Find the average number of pick ups for the...,I remember my ID code and am ready to be redir...,MAAS average
1,02/02/2024 07:09,02/02/2024 07:22,0,46.6.24.68,100,761,1,02/02/2024 07:22,R_8uL4Nge1LfhSLBw,NaN,...,44,70,54,39,43,42,48,NaN,NaN,3.933333333
2,02/02/2024 11:08,02/02/2024 11:15,0,37.170.18.99,100,430,1,02/02/2024 11:15,R_5NCAvgXFZ1RVSel,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.266666667
3,03/02/2024 09:22,03/02/2024 09:34,0,176.128.28.112,100,717,1,03/02/2024 09:34,R_2JezZk0AxtgmgxP,NaN,...,45,46,47,75,53,38,52,NaN,NaN,4.8
4,03/02/2024 09:47,03/02/2024 09:57,0,176.128.28.112,100,582,1,03/02/2024 09:57,R_5et9hiLfLEfHEXz,NaN,...,86,86,140,149,55,59,78,NaN,NaN,3.666666667

### Renaming Columsn according tp pyhton standars

In [5]:
df.columns

Index(['StartDate', 'EndDate', 'Status', 'IPAddress', 'Progress',
       'Duration (in seconds)', 'Finished', 'RecordedDate', 'ResponseId',
       'RecipientLastName', 'RecipientFirstName', 'RecipientEmail',
       'ExternalReference', 'LocationLatitude', 'LocationLongitude',
       'DistributionChannel', 'UserLanguage', 'Q for consent ',
       'Confirm consent ', 'ID Code ', 'Gender ', 'Occupation ', 'Education ',
       'Age ', 'Questionnaire_1', 'Questionnaire_2', 'Questionnaire_3',
       'Questionnaire_4', 'Questionnaire_5', 'Questionnaire_6',
       'Questionnaire_7', 'Questionnaire_8', 'Questionnaire_9',
       'Questionnaire_10', 'Questionnaire_11', 'Questionnaire_12',
       'Questionnaire_13', 'Questionnaire_14', 'Questionnaire_15', 'PCF 2 ',
       'Device', 'S.M', 'S.T ', 'S.W ', 'S.Th ', 'S.F ', 'S.S ', 'S.Su ',
       'A.M ', 'A.T ', 'A.W ', 'A.Th ', 'A.F ', 'A.S ', 'A.Su ',
       'IOS pick-ups', 'Q62', 'MAAS average'],
      dtype='object')

In [6]:
df.rename(columns={
    'StartDate': 'start_date',
    'EndDate': 'end_date',
    'Status': 'status',
    'IPAddress': 'ip_address',
    'Progress': 'progress',
    'Duration (in seconds)': 'duration_seconds',
    'Finished': 'finished',
    'RecordedDate': 'recorded_date',
    'ResponseId': 'response_id',
    'RecipientLastName': 'recipient_last_name',
    'RecipientFirstName': 'recipient_first_name',
    'RecipientEmail': 'recipient_email',
    'ExternalReference': 'external_reference',
    'LocationLatitude': 'latitude',
    'LocationLongitude': 'longitude',
    'DistributionChannel': 'distribution_channel',
    'UserLanguage': 'user_language',
    'Q for consent ': 'consent',
    'Confirm consent ': 'consent_confirmed',
    'ID Code ': 'participant_id',
    'Gender ': 'gender',
    'Occupation ': 'occupation',
    'Education ': 'education',
    'Age ': 'age',
    'PCF 2 ': 'phone_checking_frequency',
    'Device': 'device',
    'S.M': 'screen_time_mon',
    'S.T ': 'screen_time_tue',
    'S.W ': 'screen_time_wed',
    'S.Th ': 'screen_time_thu',
    'S.F ': 'screen_time_fri',
    'S.S ': 'screen_time_sat',
    'S.Su ': 'screen_time_sun',
    'A.M ': 'pickups_mon',
    'A.T ': 'pickups_tue',
    'A.W ': 'pickups_wed',
    'A.Th ': 'pickups_thu',
    'A.F ': 'pickups_fri',
    'A.S ': 'pickups_sat',
    'A.Su ': 'pickups_sun',
    'IOS pick-ups': 'ios_pickups',
    'Q62': 'q62',
    'MAAS average': 'maas_score',
}, inplace=True)

In [7]:
pd.set_option('display.max_columns', None)
df.head()

,start_date,end_date,status,ip_address,progress,duration_seconds,finished,recorded_date,response_id,recipient_last_name,recipient_first_name,recipient_email,external_reference,latitude,longitude,distribution_channel,user_language,consent,consent_confirmed,participant_id,gender,occupation,education,age,Questionnaire_1,Questionnaire_2,Questionnaire_3,Questionnaire_4,Questionnaire_5,Questionnaire_6,Questionnaire_7,Questionnaire_8,Questionnaire_9,Questionnaire_10,Questionnaire_11,Questionnaire_12,Questionnaire_13,Questionnaire_14,Questionnaire_15,phone_checking_frequency,device,screen_time_mon,S.T,screen_time_wed,screen_time_thu,screen_time_fri,screen_time_sat,screen_time_sun,pickups_mon,pickups_tue,pickups_wed,pickups_thu,pickups_fri,pickups_sat,A.Su,ios_pickups,q62,maas_score
0,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,Recipient First Name,Recipient Email,External Data Reference,Location Latitude,Location Longitude,Distribution Channel,User Language,Statement of Informed Consent,I have read and understand the above statement...,Please create your unique identifier code by u...,What gender do you identify as:,Which of the following best describes your emp...,Which of the following best describes your hig...,What is your age?,MAAS - I could be experiencing some emotion an...,MAAS - I break or spill things because of care...,MAAS - I find it difficult to stay focused on ...,MAAS - I tend to walk quickly to get where I’m...,MAAS - I tend not to notice feelings of physic...,MAAS - I forget a person’s name almost as soon...,"MAAS - It seems I am “running on automatic,” w...",MAAS - I rush through activities without being...,MAAS - I get so focused on the goal I want to ...,"MAAS - I do jobs or tasks automatically, witho...",MAAS - I find myself listening to someone with...,MAAS - I drive places on ‘automatic pilot’ and...,MAAS - I find myself preoccupied with the futu...,MAAS - I find myself doing things without payi...,MAAS - I snack without being aware that I’m ea...,"Firstly, are you using more than one device?",What type of device are you using?,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,6. Find the average number of pick ups for the...,I remember my ID code and am ready to be redir...,MAAS average
1,02/02/2024 07:09,02/02/2024 07:22,0,46.6.24.68,100,761,1,02/02/2024 07:22,R_8uL4Nge1LfhSLBw,NaN,NaN,NaN,NaN,36.6183,-4.4963,anonymous,EN,"1,2,3,4,5,6",1,PA651,2,1,3,34,3,5,4,4,4,6,4,4,4,5,3,4,3,4,2,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44,70,54,39,43,42,48,NaN,NaN,3.933333333
2,02/02/2024 11:08,02/02/2024 11:15,0,37.170.18.99,100,430,1,02/02/2024 11:15,R_5NCAvgXFZ1RVSel,NaN,NaN,NaN,NaN,48.8582,2.3387,anonymous,EN,"1,2,3,4,5,6",1,Fer01,1,1,1,32,3,3,4,1,2,3,2,2,1,2,2,2,2,2,3,2,3,86,66,80,72,137,102,64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.266666667
3,03/02/2024 09:22,03/02/2024 09:34,0,176.128.28.112,100,717,1,03/02/2024 09:34,R_2JezZk0AxtgmgxP,NaN,NaN,NaN,NaN,49.0291,2.0601,anonymous,EN,"1,2,3,4,5,6",1,pm492,1,1,6,29,6,6,6,1,4,6,4,5,4,5,5,6,3,5,6,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45,46,47,75,53,38,52,NaN,NaN,4.8
4,03/02/2024 09:47,03/02/2024 09:57,0,176.128.28.112,100,582,1,03/02/2024 09:57,R_5et9hiLfLEfHEXz,NaN,NaN,NaN,NaN,49.0291,2.0601,anonymous,EN,"1,2,3,4,5,6",1,ML194,2,1,2,29,3,6,4,2,3,5,4,4,4,4,3,4,2,3,4,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86,86,140,149,55,59,78,NaN,NaN,3.666666667

In [8]:
# Saving the cleaned DataFrame to a new CSV file
output_file_name = "Qualtrics_raw.csv"
df.to_csv(os.path.join(OUTPUT_FOLDER_PATH, output_file_name), index=False)

In [9]:
print([col for col in df.columns if 'S.T' in col or 'A.Su' in col])

['S.T\xa0', 'A.Su\xa0']

In [10]:
# Rename columns with non-breaking space characters
df.rename(columns={'S.T\xa0': 'screen_time_tue', 'A.Su\xa0': 'pickups_sun'}, inplace=True)

In [11]:
# Saving the cleaned DataFrame to a new CSV file
output_file_name = "Qualtrics_raw.csv"
df.to_csv(os.path.join(OUTPUT_FOLDER_PATH, output_file_name), index=False)

## Data cleaning

In [12]:
file_name = "Qualtrics_raw.csv"
df = pd.read_csv(f"/Users/remyfernando/Desktop/Noguchi Active/BSc Psychology/Year 3/Research Project/Project data/{file_name}")

### Changing device type values from numerical to actual Names

In [13]:
# First converting column to numeric
df["device"] = pd.to_numeric(df["device"], errors='coerce')
df["device"].dtypes

# Then changing device types to names
df['device'] = df['device'].astype(object)
df.loc[df['device'] == 1, 'device'] = 'iPhone'
df.loc[df['device'] == 2, 'device'] = 'Android'
df.loc[df['device'] == 3, 'device'] = 'Samsung'

df.head(20)

,start_date,end_date,status,ip_address,progress,duration_seconds,finished,recorded_date,response_id,recipient_last_name,recipient_first_name,recipient_email,external_reference,latitude,longitude,distribution_channel,user_language,consent,consent_confirmed,participant_id,gender,occupation,education,age,Questionnaire_1,Questionnaire_2,Questionnaire_3,Questionnaire_4,Questionnaire_5,Questionnaire_6,Questionnaire_7,Questionnaire_8,Questionnaire_9,Questionnaire_10,Questionnaire_11,Questionnaire_12,Questionnaire_13,Questionnaire_14,Questionnaire_15,phone_checking_frequency,device,screen_time_mon,screen_time_tue,screen_time_wed,screen_time_thu,screen_time_fri,screen_time_sat,screen_time_sun,pickups_mon,pickups_tue,pickups_wed,pickups_thu,pickups_fri,pickups_sat,pickups_sun,ios_pickups,q62,maas_score
0,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,Recipient First Name,Recipient Email,External Data Reference,Location Latitude,Location Longitude,Distribution Channel,User Language,Statement of Informed Consent,I have read and understand the above statement...,Please create your unique identifier code by u...,What gender do you identify as:,Which of the following best describes your emp...,Which of the following best describes your hig...,What is your age?,MAAS - I could be experiencing some emotion an...,MAAS - I break or spill things because of care...,MAAS - I find it difficult to stay focused on ...,MAAS - I tend to walk quickly to get where I’m...,MAAS - I tend not to notice feelings of physic...,MAAS - I forget a person’s name almost as soon...,"MAAS - It seems I am “running on automatic,” w...",MAAS - I rush through activities without being...,MAAS - I get so focused on the goal I want to ...,"MAAS - I do jobs or tasks automatically, witho...",MAAS - I find myself listening to someone with...,MAAS - I drive places on ‘automatic pilot’ and...,MAAS - I find myself preoccupied with the futu...,MAAS - I find myself doing things without payi...,MAAS - I snack without being aware that I’m ea...,"Firstly, are you using more than one device?",NaN,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,6. Find the average number of pick ups for the...,I remember my ID code and am ready to be redir...,MAAS average
1,02/02/2024 07:09,02/02/2024 07:22,0,46.6.24.68,100,761,1,02/02/2024 07:22,R_8uL4Nge1LfhSLBw,NaN,NaN,NaN,NaN,36.6183,-4.4963,anonymous,EN,"1,2,3,4,5,6",1,PA651,2,1,3,34,3,5,4,4,4,6,4,4,4,5,3,4,3,4,2,1,Android,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44,70,54,39,43,42,48,NaN,NaN,3.933333333
2,02/02/2024 11:08,02/02/2024 11:15,0,37.170.18.99,100,430,1,02/02/2024 11:15,R_5NCAvgXFZ1RVSel,NaN,NaN,NaN,NaN,48.8582,2.3387,anonymous,EN,"1,2,3,4,5,6",1,Fer01,1,1,1,32,3,3,4,1,2,3,2,2,1,2,2,2,2,2,3,2,Samsung,86,66,80,72,137,102,64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.266666667
3,03/02/2024 09:22,03/02/2024 09:34,0,176.128.28.112,100,717,1,03/02/2024 09:34,R_2JezZk0AxtgmgxP,NaN,NaN,NaN,NaN,49.0291,2.0601,anonymous,EN,"1,2,3,4,5,6",1,pm492,1,1,6,29,6,6,6,1,4,6,4,5,4,5,5,6,3,5,6,2,Android,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45,46,47,75,53,38,52,NaN,NaN,4.8
4,03/02/2024 09:47,03/02/2024 09:57,0,176.128.28.112,100,582,1,03/02/2024 09:57,R_5et9hiLfLEfHEXz,NaN,NaN,NaN,NaN,49.0291,2.0601,anonymous,EN,"1,2,3,4,5,6",1,ML194,2,1,2,29,3,6,4,2,3,5,4,4,4,4,3,4,2,3,4,1,Android,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86,86,140,149,55,59,78,NaN,NaN,3.666666667
5,04/02/2024 11:16,04/02/2024 11:21,0,2.13.222.101,100,284,1,04/02/2024 11:21,R_2qlOCOgnUZCbzPD,NaN,NaN,NaN,NaN,48.8316,2.4839,anonymous,EN,"1,2,3,4,5,6",1,FER13,1,2,1,32,2,3,4,2,2,2,2,2,3,3,2,3,4,2,4,1,Samsung,88,80,50,88,126,124,120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.666666667
6,04/02/2024 13:35,04/02/2024 13:45,0,80.99.14.63,100,624,1,04/02/2024 13:45,R_1P6dHLvKXX632cY,NaN,NaN,NaN,NaN,47.5636,19.0947,anonymous,EN,"1,2,3,4,5,6",1,KE831,2,4,2,32,3,3,4,3,4,2,3,3,3,3,2,5,2,3,4,2,Android,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19,46,37,43,46,26,27,NaN,NaN,3.133333333
7,05/02/2024 11:22,05/02/2024 11:34,0,176.172.45.229,100,746,1,05/02/2024 11:34,R_4rk3tW7gPZEmAZH,NaN,NaN,NaN,NaN,43.6046,1.4451,anonymous,EN,"1,2,3,4,5,6",1,PA741,1,1,3,34,5,6,4,4,5,5,5,5,3,3,2,5,1,4,6,2,Android,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52,56,66,68,67,40,36,NaN,NaN,4.2
8,05/02/2024 13:54,05/02/2024 14:39,0,91.170.90.96,100,2733,1,05/02/2024 14:39,R_374iDNfav2nuhy1,NaN,NaN,NaN,NaN,49.0291,2.0601,anonymous,EN,"1,2,3,4,5,6",1,RI500,2,1,2,46,3,5,5,4,3,6,5,5,3,6,2,6,2,4,6,1,Android,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63,113,93,108,101,93,84,NaN,NaN,4.333333333
9,06/02/2024 04:32,06/02/2024 04:37,0,2.219.117.237,100,249,1,06/02/2024 04:37,R_8qw1xHO3de5lPo4,NaN,NaN,NaN,NaN,52.9029,-1.5046,anonymous,EN,"1,2,3,4,5,6",1,PI945,2,6,8,21,4,2,2,1,3,5,2,2,3,3,2,6,2,3,4,2,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,215,NaN,2.933333333
10,07/02/2024 08:41,07/02/2024 08:48,0,176.142.38.92,100,373,1,07/02/2024 08:48,R_4JY3W69wKFSNv3Z,NaN,NaN,NaN,NaN,48.8323,2.4075,anonymous,EN,"1,2,3,4,5,6",1,ES663,2,1,2,33,3,6,3,5,5,6,5,5,4,4,5,5,2,5,6,1,Samsung,41,36,46,42,64,69,73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.6
11,08/02/2024 05:20,08/02/2024 05:26,0,49.228.56.15,100,379,1,08/02/2024 05:26,R_4diHwapgP7OhYZX,NaN,NaN,NaN,NaN,13.0508,100.9367,anonymous,EN,"1,2,3,4,5,6",1,WE718,2,6,6,22,3,5,5,4,5,5,3,5,4,3,3,4,4,3,4,1,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88,NaN,4
12,08/02/2024 09:16,08/02/2024 09:27,0,88.203.6.215,100,629,1,08/02/2024 09:27,R_5F4FV9IB6HHaar9,NaN,NaN,NaN,NaN,35.8246,14.5309,anonymous,EN,"1,2,3,4,5,6",1,JO029,2,1,6,43,2,4,5,3,3,4,5,5,5,5,4,4,3,5,5,2,Android,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58,42,36,46,46,31,33,NaN,1,4.133333333
13,09/02/2024 00:45,09/02/2024 01:00,0,86.97.134.112,100,902,1,09/02/2024 01:00,R_49dmTwV5GiPNvQ5,NaN,NaN,NaN,NaN,24.4542,54.406,anonymous,EN,"1,2,3,4,5,6",1,AG115,2,4,3,35,2,2,2,3,2,2,3,3,3,3,4,5,2,3,3,2,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,152,1,2.8
14,08/02/2024 11:37,09/02/2024 07:48,0,104.173.11.215,100,72707,1,09/02/2024 07:48,R_6q3X6HuehoXdGzG,NaN,NaN,NaN,NaN,34.1979,-118.5371,anonymous,EN,"1,2,3,4,5,6",1,Ja735,1,1,3,39,3,5,4,5,3,3,4,4,5,4,4,5,2,5,5,1,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,179,1,4.066666667
15,09/02/2024 09:02,09/02/2024 09:05,0,104.173.11.215,100,173,1,09/02/2024 09:05,R_3LqIKjU3J4AuDv5,NaN,NaN,NaN,NaN,34.1979,-118.5371,anonymous,EN,"1,2,3,4,5,6",1,ja735,1,1,3,39,4,5,4,5,4,4,4,4,5,5,4,5,3,4,5,1,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,172,1,4.333333333
16,10/02/2024 09:29,10/02/2024 09:35,0,80.214.56.197,100,344,1,10/02/2024 09:35,R_7gQRRn6I7kxmWVH,NaN,NaN,NaN,NaN,48.8323,2.4075,anonymous,EN,"1,2,3,4,5,6",1,PA741,1,1,3,34,5,5,4,5,5,3,4,4,3,4,2,5,1,4,6,2,Android,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52,56,66,68,67,40,36,NaN,1,4
17,10/02/2024 09:47,10/02/2024 09:58,0,89.85.245.0,100,623,1,10/02/2024 09:58,R_5MCbBXl5Pi2wCAh,NaN,NaN,NaN,NaN,48.9275,2.3623,anonymous,EN,"1,2,3,4,5,6",1,BA664,2,1,2,33,5,5,2,5,6,1,4,6,3,5,5,5,3,5,6,1,Android,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69,82,61,70,41,38,39,NaN,1,4.4
18,10/02/2024 11:06,10/02/2024 11:59,0,2.58.72.131,100,3209,1,10/02/2024 11:59,R_2qMNVqZUePoHMD7,NaN,NaN,NaN,NaN,51.5088,-0.093,anonymous,EN,"1,2,3,4,5,6",1,RY303,1,1,2,24,6,6,2,3,4,1,2,4,5,4,3,6,2,3,6,1,Android,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39,49,42,59,32,26,29,NaN,1,3.8
19,11/02/2024 20:13,11/02/2024 20:20,0,82.30.148.144,100,458,1,11/02/2024 20:20,R_5sZOANIm8HaOXXn,NaN,NaN,NaN,NaN,53.4003,-2.2154,anonymous,EN,"1,2,3,4,5,6",1,AL554,2,3,3,47,5,6,6,6,6,6,6,6,6,6,6,6,6,6,6,2,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102,1,5.933333333

## Cleaning pick-up columns
There were two different set of weekdays day, one for Android and. one for Samsung. This was because of Qualtrics set-up which collected differently based on device.
Merging both Samsung and Android data into the same 7 columns for each days collected

In [14]:
print("Samsung")
print(df[df['device'] == 'Samsung'][['screen_time_mon', 'pickups_mon']].head(3))
print("android")
print(df[df['device'] == 'Android'][['screen_time_mon', 'pickups_mon']].head(3))

Samsung
   screen_time_mon pickups_mon
2               86         NaN
5               88         NaN
10              41         NaN
android
  screen_time_mon pickups_mon
1             NaN          44
3             NaN          45
4             NaN          86

In [15]:
days = ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']

for day in days:
    df.loc[df['device'] == 'Samsung', f'pickups_{day}'] = df.loc[df['device'] == 'Samsung', f'screen_time_{day}']

In [16]:
df.head(20)

,start_date,end_date,status,ip_address,progress,duration_seconds,finished,recorded_date,response_id,recipient_last_name,recipient_first_name,recipient_email,external_reference,latitude,longitude,distribution_channel,user_language,consent,consent_confirmed,participant_id,gender,occupation,education,age,Questionnaire_1,Questionnaire_2,Questionnaire_3,Questionnaire_4,Questionnaire_5,Questionnaire_6,Questionnaire_7,Questionnaire_8,Questionnaire_9,Questionnaire_10,Questionnaire_11,Questionnaire_12,Questionnaire_13,Questionnaire_14,Questionnaire_15,phone_checking_frequency,device,screen_time_mon,screen_time_tue,screen_time_wed,screen_time_thu,screen_time_fri,screen_time_sat,screen_time_sun,pickups_mon,pickups_tue,pickups_wed,pickups_thu,pickups_fri,pickups_sat,pickups_sun,ios_pickups,q62,maas_score
0,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,Recipient First Name,Recipient Email,External Data Reference,Location Latitude,Location Longitude,Distribution Channel,User Language,Statement of Informed Consent,I have read and understand the above statement...,Please create your unique identifier code by u...,What gender do you identify as:,Which of the following best describes your emp...,Which of the following best describes your hig...,What is your age?,MAAS - I could be experiencing some emotion an...,MAAS - I break or spill things because of care...,MAAS - I find it difficult to stay focused on ...,MAAS - I tend to walk quickly to get where I’m...,MAAS - I tend not to notice feelings of physic...,MAAS - I forget a person’s name almost as soon...,"MAAS - It seems I am “running on automatic,” w...",MAAS - I rush through activities without being...,MAAS - I get so focused on the goal I want to ...,"MAAS - I do jobs or tasks automatically, witho...",MAAS - I find myself listening to someone with...,MAAS - I drive places on ‘automatic pilot’ and...,MAAS - I find myself preoccupied with the futu...,MAAS - I find myself doing things without payi...,MAAS - I snack without being aware that I’m ea...,"Firstly, are you using more than one device?",NaN,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,6. Find the average number of pick ups for the...,I remember my ID code and am ready to be redir...,MAAS average
1,02/02/2024 07:09,02/02/2024 07:22,0,46.6.24.68,100,761,1,02/02/2024 07:22,R_8uL4Nge1LfhSLBw,NaN,NaN,NaN,NaN,36.6183,-4.4963,anonymous,EN,"1,2,3,4,5,6",1,PA651,2,1,3,34,3,5,4,4,4,6,4,4,4,5,3,4,3,4,2,1,Android,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44,70,54,39,43,42,48,NaN,NaN,3.933333333
2,02/02/2024 11:08,02/02/2024 11:15,0,37.170.18.99,100,430,1,02/02/2024 11:15,R_5NCAvgXFZ1RVSel,NaN,NaN,NaN,NaN,48.8582,2.3387,anonymous,EN,"1,2,3,4,5,6",1,Fer01,1,1,1,32,3,3,4,1,2,3,2,2,1,2,2,2,2,2,3,2,Samsung,86,66,80,72,137,102,64,86,66,80,72,137,102,64,NaN,NaN,2.266666667
3,03/02/2024 09:22,03/02/2024 09:34,0,176.128.28.112,100,717,1,03/02/2024 09:34,R_2JezZk0AxtgmgxP,NaN,NaN,NaN,NaN,49.0291,2.0601,anonymous,EN,"1,2,3,4,5,6",1,pm492,1,1,6,29,6,6,6,1,4,6,4,5,4,5,5,6,3,5,6,2,Android,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45,46,47,75,53,38,52,NaN,NaN,4.8
4,03/02/2024 09:47,03/02/2024 09:57,0,176.128.28.112,100,582,1,03/02/2024 09:57,R_5et9hiLfLEfHEXz,NaN,NaN,NaN,NaN,49.0291,2.0601,anonymous,EN,"1,2,3,4,5,6",1,ML194,2,1,2,29,3,6,4,2,3,5,4,4,4,4,3,4,2,3,4,1,Android,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86,86,140,149,55,59,78,NaN,NaN,3.666666667
5,04/02/2024 11:16,04/02/2024 11:21,0,2.13.222.101,100,284,1,04/02/2024 11:21,R_2qlOCOgnUZCbzPD,NaN,NaN,NaN,NaN,48.8316,2.4839,anonymous,EN,"1,2,3,4,5,6",1,FER13,1,2,1,32,2,3,4,2,2,2,2,2,3,3,2,3,4,2,4,1,Samsung,88,80,50,88,126,124,120,88,80,50,88,126,124,120,NaN,NaN,2.666666667
6,04/02/2024 13:35,04/02/2024 13:45,0,80.99.14.63,100,624,1,04/02/2024 13:45,R_1P6dHLvKXX632cY,NaN,NaN,NaN,NaN,47.5636,19.0947,anonymous,EN,"1,2,3,4,5,6",1,KE831,2,4,2,32,3,3,4,3,4,2,3,3,3,3,2,5,2,3,4,2,Android,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19,46,37,43,46,26,27,NaN,NaN,3.133333333
7,05/02/2024 11:22,05/02/2024 11:34,0,176.172.45.229,100,746,1,05/02/2024 11:34,R_4rk3tW7gPZEmAZH,NaN,NaN,NaN,NaN,43.6046,1.4451,anonymous,EN,"1,2,3,4,5,6",1,PA741,1,1,3,34,5,6,4,4,5,5,5,5,3,3,2,5,1,4,6,2,Android,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52,56,66,68,67,40,36,NaN,NaN,4.2
8,05/02/2024 13:54,05/02/2024 14:39,0,91.170.90.96,100,2733,1,05/02/2024 14:39,R_374iDNfav2nuhy1,NaN,NaN,NaN,NaN,49.0291,2.0601,anonymous,EN,"1,2,3,4,5,6",1,RI500,2,1,2,46,3,5,5,4,3,6,5,5,3,6,2,6,2,4,6,1,Android,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63,113,93,108,101,93,84,NaN,NaN,4.333333333
9,06/02/2024 04:32,06/02/2024 04:37,0,2.219.117.237,100,249,1,06/02/2024 04:37,R_8qw1xHO3de5lPo4,NaN,NaN,NaN,NaN,52.9029,-1.5046,anonymous,EN,"1,2,3,4,5,6",1,PI945,2,6,8,21,4,2,2,1,3,5,2,2,3,3,2,6,2,3,4,2,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,215,NaN,2.933333333
10,07/02/2024 08:41,07/02/2024 08:48,0,176.142.38.92,100,373,1,07/02/2024 08:48,R_4JY3W69wKFSNv3Z,NaN,NaN,NaN,NaN,48.8323,2.4075,anonymous,EN,"1,2,3,4,5,6",1,ES663,2,1,2,33,3,6,3,5,5,6,5,5,4,4,5,5,2,5,6,1,Samsung,41,36,46,42,64,69,73,41,36,46,42,64,69,73,NaN,NaN,4.6
11,08/02/2024 05:20,08/02/2024 05:26,0,49.228.56.15,100,379,1,08/02/2024 05:26,R_4diHwapgP7OhYZX,NaN,NaN,NaN,NaN,13.0508,100.9367,anonymous,EN,"1,2,3,4,5,6",1,WE718,2,6,6,22,3,5,5,4,5,5,3,5,4,3,3,4,4,3,4,1,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88,NaN,4
12,08/02/2024 09:16,08/02/2024 09:27,0,88.203.6.215,100,629,1,08/02/2024 09:27,R_5F4FV9IB6HHaar9,NaN,NaN,NaN,NaN,35.8246,14.5309,anonymous,EN,"1,2,3,4,5,6",1,JO029,2,1,6,43,2,4,5,3,3,4,5,5,5,5,4,4,3,5,5,2,Android,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58,42,36,46,46,31,33,NaN,1,4.133333333
13,09/02/2024 00:45,09/02/2024 01:00,0,86.97.134.112,100,902,1,09/02/2024 01:00,R_49dmTwV5GiPNvQ5,NaN,NaN,NaN,NaN,24.4542,54.406,anonymous,EN,"1,2,3,4,5,6",1,AG115,2,4,3,35,2,2,2,3,2,2,3,3,3,3,4,5,2,3,3,2,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,152,1,2.8
14,08/02/2024 11:37,09/02/2024 07:48,0,104.173.11.215,100,72707,1,09/02/2024 07:48,R_6q3X6HuehoXdGzG,NaN,NaN,NaN,NaN,34.1979,-118.5371,anonymous,EN,"1,2,3,4,5,6",1,Ja735,1,1,3,39,3,5,4,5,3,3,4,4,5,4,4,5,2,5,5,1,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,179,1,4.066666667
15,09/02/2024 09:02,09/02/2024 09:05,0,104.173.11.215,100,173,1,09/02/2024 09:05,R_3LqIKjU3J4AuDv5,NaN,NaN,NaN,NaN,34.1979,-118.5371,anonymous,EN,"1,2,3,4,5,6",1,ja735,1,1,3,39,4,5,4,5,4,4,4,4,5,5,4,5,3,4,5,1,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,172,1,4.333333333
16,10/02/2024 09:29,10/02/2024 09:35,0,80.214.56.197,100,344,1,10/02/2024 09:35,R_7gQRRn6I7kxmWVH,NaN,NaN,NaN,NaN,48.8323,2.4075,anonymous,EN,"1,2,3,4,5,6",1,PA741,1,1,3,34,5,5,4,5,5,3,4,4,3,4,2,5,1,4,6,2,Android,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52,56,66,68,67,40,36,NaN,1,4
17,10/02/2024 09:47,10/02/2024 09:58,0,89.85.245.0,100,623,1,10/02/2024 09:58,R_5MCbBXl5Pi2wCAh,NaN,NaN,NaN,NaN,48.9275,2.3623,anonymous,EN,"1,2,3,4,5,6",1,BA664,2,1,2,33,5,5,2,5,6,1,4,6,3,5,5,5,3,5,6,1,Android,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69,82,61,70,41,38,39,NaN,1,4.4
18,10/02/2024 11:06,10/02/2024 11:59,0,2.58.72.131,100,3209,1,10/02/2024 11:59,R_2qMNVqZUePoHMD7,NaN,NaN,NaN,NaN,51.5088,-0.093,anonymous,EN,"1,2,3,4,5,6",1,RY303,1,1,2,24,6,6,2,3,4,1,2,4,5,4,3,6,2,3,6,1,Android,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39,49,42,59,32,26,29,NaN,1,3.8
19,11/02/2024 20:13,11/02/2024 20:20,0,82.30.148.144,100,458,1,11/02/2024 20:20,R_5sZOANIm8HaOXXn,NaN,NaN,NaN,NaN,53.4003,-2.2154,anonymous,EN,"1,2,3,4,5,6",1,AL554,2,3,3,47,5,6,6,6,6,6,6,6,6,6,6,6,6,6,6,2,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102,1,5.933333333

In [17]:
df.columns

Index(['start_date', 'end_date', 'status', 'ip_address', 'progress',
       'duration_seconds', 'finished', 'recorded_date', 'response_id',
       'recipient_last_name', 'recipient_first_name', 'recipient_email',
       'external_reference', 'latitude', 'longitude', 'distribution_channel',
       'user_language', 'consent', 'consent_confirmed', 'participant_id',
       'gender', 'occupation', 'education', 'age', 'Questionnaire_1',
       'Questionnaire_2', 'Questionnaire_3', 'Questionnaire_4',
       'Questionnaire_5', 'Questionnaire_6', 'Questionnaire_7',
       'Questionnaire_8', 'Questionnaire_9', 'Questionnaire_10',
       'Questionnaire_11', 'Questionnaire_12', 'Questionnaire_13',
       'Questionnaire_14', 'Questionnaire_15', 'phone_checking_frequency',
       'device', 'screen_time_mon', 'screen_time_tue', 'screen_time_wed',
       'screen_time_thu', 'screen_time_fri', 'screen_time_sat',
       'screen_time_sun', 'pickups_mon', 'pickups_tue', 'pickups_wed',
       'pickups_thu', 'pickups_fri', 'pickups_sat', 'pickups_sun',
       'ios_pickups', 'q62', 'maas_score'],
      dtype='object')

In [18]:
screentime_cols = [col for col in df.columns if 'screen_time' in col]
print(screentime_cols)

['screen_time_mon', 'screen_time_tue', 'screen_time_wed', 'screen_time_thu', 'screen_time_fri', 'screen_time_sat', 'screen_time_sun']

In [19]:
df.drop(columns=screentime_cols, inplace=True)
df.columns

Index(['start_date', 'end_date', 'status', 'ip_address', 'progress',
       'duration_seconds', 'finished', 'recorded_date', 'response_id',
       'recipient_last_name', 'recipient_first_name', 'recipient_email',
       'external_reference', 'latitude', 'longitude', 'distribution_channel',
       'user_language', 'consent', 'consent_confirmed', 'participant_id',
       'gender', 'occupation', 'education', 'age', 'Questionnaire_1',
       'Questionnaire_2', 'Questionnaire_3', 'Questionnaire_4',
       'Questionnaire_5', 'Questionnaire_6', 'Questionnaire_7',
       'Questionnaire_8', 'Questionnaire_9', 'Questionnaire_10',
       'Questionnaire_11', 'Questionnaire_12', 'Questionnaire_13',
       'Questionnaire_14', 'Questionnaire_15', 'phone_checking_frequency',
       'device', 'pickups_mon', 'pickups_tue', 'pickups_wed', 'pickups_thu',
       'pickups_fri', 'pickups_sat', 'pickups_sun', 'ios_pickups', 'q62',
       'maas_score'],
      dtype='object')

In [20]:
questionaire_columns = [ 'Questionnaire_1',
       'Questionnaire_2', 'Questionnaire_3', 'Questionnaire_4',
       'Questionnaire_5', 'Questionnaire_6', 'Questionnaire_7',
       'Questionnaire_8', 'Questionnaire_9', 'Questionnaire_10',
       'Questionnaire_11', 'Questionnaire_12', 'Questionnaire_13',
       'Questionnaire_14', 'Questionnaire_15',
       ]
print(questionaire_columns)

['Questionnaire_1', 'Questionnaire_2', 'Questionnaire_3', 'Questionnaire_4', 'Questionnaire_5', 'Questionnaire_6', 'Questionnaire_7', 'Questionnaire_8', 'Questionnaire_9', 'Questionnaire_10', 'Questionnaire_11', 'Questionnaire_12', 'Questionnaire_13', 'Questionnaire_14', 'Questionnaire_15']

In [21]:
df.drop(columns=questionaire_columns, inplace=True)
df.columns

Index(['start_date', 'end_date', 'status', 'ip_address', 'progress',
       'duration_seconds', 'finished', 'recorded_date', 'response_id',
       'recipient_last_name', 'recipient_first_name', 'recipient_email',
       'external_reference', 'latitude', 'longitude', 'distribution_channel',
       'user_language', 'consent', 'consent_confirmed', 'participant_id',
       'gender', 'occupation', 'education', 'age', 'phone_checking_frequency',
       'device', 'pickups_mon', 'pickups_tue', 'pickups_wed', 'pickups_thu',
       'pickups_fri', 'pickups_sat', 'pickups_sun', 'ios_pickups', 'q62',
       'maas_score'],
      dtype='object')

In [22]:
df.head()

,start_date,end_date,status,ip_address,progress,duration_seconds,finished,recorded_date,response_id,recipient_last_name,recipient_first_name,recipient_email,external_reference,latitude,longitude,distribution_channel,user_language,consent,consent_confirmed,participant_id,gender,occupation,education,age,phone_checking_frequency,device,pickups_mon,pickups_tue,pickups_wed,pickups_thu,pickups_fri,pickups_sat,pickups_sun,ios_pickups,q62,maas_score
0,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,Recipient First Name,Recipient Email,External Data Reference,Location Latitude,Location Longitude,Distribution Channel,User Language,Statement of Informed Consent,I have read and understand the above statement...,Please create your unique identifier code by u...,What gender do you identify as:,Which of the following best describes your emp...,Which of the following best describes your hig...,What is your age?,"Firstly, are you using more than one device?",NaN,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,6. Find the average number of pick ups for the...,I remember my ID code and am ready to be redir...,MAAS average
1,02/02/2024 07:09,02/02/2024 07:22,0,46.6.24.68,100,761,1,02/02/2024 07:22,R_8uL4Nge1LfhSLBw,NaN,NaN,NaN,NaN,36.6183,-4.4963,anonymous,EN,"1,2,3,4,5,6",1,PA651,2,1,3,34,1,Android,44,70,54,39,43,42,48,NaN,NaN,3.933333333
2,02/02/2024 11:08,02/02/2024 11:15,0,37.170.18.99,100,430,1,02/02/2024 11:15,R_5NCAvgXFZ1RVSel,NaN,NaN,NaN,NaN,48.8582,2.3387,anonymous,EN,"1,2,3,4,5,6",1,Fer01,1,1,1,32,2,Samsung,86,66,80,72,137,102,64,NaN,NaN,2.266666667
3,03/02/2024 09:22,03/02/2024 09:34,0,176.128.28.112,100,717,1,03/02/2024 09:34,R_2JezZk0AxtgmgxP,NaN,NaN,NaN,NaN,49.0291,2.0601,anonymous,EN,"1,2,3,4,5,6",1,pm492,1,1,6,29,2,Android,45,46,47,75,53,38,52,NaN,NaN,4.8
4,03/02/2024 09:47,03/02/2024 09:57,0,176.128.28.112,100,582,1,03/02/2024 09:57,R_5et9hiLfLEfHEXz,NaN,NaN,NaN,NaN,49.0291,2.0601,anonymous,EN,"1,2,3,4,5,6",1,ML194,2,1,2,29,1,Android,86,86,140,149,55,59,78,NaN,NaN,3.666666667

### Calculating and adding Non-IOS device pick- average column

In [23]:
days = ['pickups_mon', 'pickups_tue', 'pickups_wed', 'pickups_thu', 'pickups_fri', 'pickups_sat', 'pickups_sun']
 # Convert the pickups columns to numeric, coercing errors to NaN
for day in days:
    df[day] = pd.to_numeric(df[day], errors='coerce')

df["non_ios_avg_pickups"] = df[days].mean(axis=1).round()

# Rounding MAAS scores to 2 decimal places
df["maas_score"] = pd.to_numeric(df["maas_score"], errors='coerce').round(2)

df.head(20)

,start_date,end_date,status,ip_address,progress,duration_seconds,finished,recorded_date,response_id,recipient_last_name,recipient_first_name,recipient_email,external_reference,latitude,longitude,distribution_channel,user_language,consent,consent_confirmed,participant_id,gender,occupation,education,age,phone_checking_frequency,device,pickups_mon,pickups_tue,pickups_wed,pickups_thu,pickups_fri,pickups_sat,pickups_sun,ios_pickups,q62,maas_score,non_ios_avg_pickups
0,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,Recipient First Name,Recipient Email,External Data Reference,Location Latitude,Location Longitude,Distribution Channel,User Language,Statement of Informed Consent,I have read and understand the above statement...,Please create your unique identifier code by u...,What gender do you identify as:,Which of the following best describes your emp...,Which of the following best describes your hig...,What is your age?,"Firstly, are you using more than one device?",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6. Find the average number of pick ups for the...,I remember my ID code and am ready to be redir...,NaN,NaN
1,02/02/2024 07:09,02/02/2024 07:22,0,46.6.24.68,100,761,1,02/02/2024 07:22,R_8uL4Nge1LfhSLBw,NaN,NaN,NaN,NaN,36.6183,-4.4963,anonymous,EN,"1,2,3,4,5,6",1,PA651,2,1,3,34,1,Android,44.0,70.0,54.0,39.0,43.0,42.0,48.0,NaN,NaN,3.93,49.0
2,02/02/2024 11:08,02/02/2024 11:15,0,37.170.18.99,100,430,1,02/02/2024 11:15,R_5NCAvgXFZ1RVSel,NaN,NaN,NaN,NaN,48.8582,2.3387,anonymous,EN,"1,2,3,4,5,6",1,Fer01,1,1,1,32,2,Samsung,86.0,66.0,80.0,72.0,137.0,102.0,64.0,NaN,NaN,2.27,87.0
3,03/02/2024 09:22,03/02/2024 09:34,0,176.128.28.112,100,717,1,03/02/2024 09:34,R_2JezZk0AxtgmgxP,NaN,NaN,NaN,NaN,49.0291,2.0601,anonymous,EN,"1,2,3,4,5,6",1,pm492,1,1,6,29,2,Android,45.0,46.0,47.0,75.0,53.0,38.0,52.0,NaN,NaN,4.80,51.0
4,03/02/2024 09:47,03/02/2024 09:57,0,176.128.28.112,100,582,1,03/02/2024 09:57,R_5et9hiLfLEfHEXz,NaN,NaN,NaN,NaN,49.0291,2.0601,anonymous,EN,"1,2,3,4,5,6",1,ML194,2,1,2,29,1,Android,86.0,86.0,140.0,149.0,55.0,59.0,78.0,NaN,NaN,3.67,93.0
5,04/02/2024 11:16,04/02/2024 11:21,0,2.13.222.101,100,284,1,04/02/2024 11:21,R_2qlOCOgnUZCbzPD,NaN,NaN,NaN,NaN,48.8316,2.4839,anonymous,EN,"1,2,3,4,5,6",1,FER13,1,2,1,32,1,Samsung,88.0,80.0,50.0,88.0,126.0,124.0,120.0,NaN,NaN,2.67,97.0
6,04/02/2024 13:35,04/02/2024 13:45,0,80.99.14.63,100,624,1,04/02/2024 13:45,R_1P6dHLvKXX632cY,NaN,NaN,NaN,NaN,47.5636,19.0947,anonymous,EN,"1,2,3,4,5,6",1,KE831,2,4,2,32,2,Android,19.0,46.0,37.0,43.0,46.0,26.0,27.0,NaN,NaN,3.13,35.0
7,05/02/2024 11:22,05/02/2024 11:34,0,176.172.45.229,100,746,1,05/02/2024 11:34,R_4rk3tW7gPZEmAZH,NaN,NaN,NaN,NaN,43.6046,1.4451,anonymous,EN,"1,2,3,4,5,6",1,PA741,1,1,3,34,2,Android,52.0,56.0,66.0,68.0,67.0,40.0,36.0,NaN,NaN,4.20,55.0
8,05/02/2024 13:54,05/02/2024 14:39,0,91.170.90.96,100,2733,1,05/02/2024 14:39,R_374iDNfav2nuhy1,NaN,NaN,NaN,NaN,49.0291,2.0601,anonymous,EN,"1,2,3,4,5,6",1,RI500,2,1,2,46,1,Android,63.0,113.0,93.0,108.0,101.0,93.0,84.0,NaN,NaN,4.33,94.0
9,06/02/2024 04:32,06/02/2024 04:37,0,2.219.117.237,100,249,1,06/02/2024 04:37,R_8qw1xHO3de5lPo4,NaN,NaN,NaN,NaN,52.9029,-1.5046,anonymous,EN,"1,2,3,4,5,6",1,PI945,2,6,8,21,2,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,215,NaN,2.93,NaN
10,07/02/2024 08:41,07/02/2024 08:48,0,176.142.38.92,100,373,1,07/02/2024 08:48,R_4JY3W69wKFSNv3Z,NaN,NaN,NaN,NaN,48.8323,2.4075,anonymous,EN,"1,2,3,4,5,6",1,ES663,2,1,2,33,1,Samsung,41.0,36.0,46.0,42.0,64.0,69.0,73.0,NaN,NaN,4.60,53.0
11,08/02/2024 05:20,08/02/2024 05:26,0,49.228.56.15,100,379,1,08/02/2024 05:26,R_4diHwapgP7OhYZX,NaN,NaN,NaN,NaN,13.0508,100.9367,anonymous,EN,"1,2,3,4,5,6",1,WE718,2,6,6,22,1,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88,NaN,4.00,NaN
12,08/02/2024 09:16,08/02/2024 09:27,0,88.203.6.215,100,629,1,08/02/2024 09:27,R_5F4FV9IB6HHaar9,NaN,NaN,NaN,NaN,35.8246,14.5309,anonymous,EN,"1,2,3,4,5,6",1,JO029,2,1,6,43,2,Android,58.0,42.0,36.0,46.0,46.0,31.0,33.0,NaN,1,4.13,42.0
13,09/02/2024 00:45,09/02/2024 01:00,0,86.97.134.112,100,902,1,09/02/2024 01:00,R_49dmTwV5GiPNvQ5,NaN,NaN,NaN,NaN,24.4542,54.406,anonymous,EN,"1,2,3,4,5,6",1,AG115,2,4,3,35,2,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,152,1,2.80,NaN
14,08/02/2024 11:37,09/02/2024 07:48,0,104.173.11.215,100,72707,1,09/02/2024 07:48,R_6q3X6HuehoXdGzG,NaN,NaN,NaN,NaN,34.1979,-118.5371,anonymous,EN,"1,2,3,4,5,6",1,Ja735,1,1,3,39,1,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,179,1,4.07,NaN
15,09/02/2024 09:02,09/02/2024 09:05,0,104.173.11.215,100,173,1,09/02/2024 09:05,R_3LqIKjU3J4AuDv5,NaN,NaN,NaN,NaN,34.1979,-118.5371,anonymous,EN,"1,2,3,4,5,6",1,ja735,1,1,3,39,1,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,172,1,4.33,NaN
16,10/02/2024 09:29,10/02/2024 09:35,0,80.214.56.197,100,344,1,10/02/2024 09:35,R_7gQRRn6I7kxmWVH,NaN,NaN,NaN,NaN,48.8323,2.4075,anonymous,EN,"1,2,3,4,5,6",1,PA741,1,1,3,34,2,Android,52.0,56.0,66.0,68.0,67.0,40.0,36.0,NaN,1,4.00,55.0
17,10/02/2024 09:47,10/02/2024 09:58,0,89.85.245.0,100,623,1,10/02/2024 09:58,R_5MCbBXl5Pi2wCAh,NaN,NaN,NaN,NaN,48.9275,2.3623,anonymous,EN,"1,2,3,4,5,6",1,BA664,2,1,2,33,1,Android,69.0,82.0,61.0,70.0,41.0,38.0,39.0,NaN,1,4.40,57.0
18,10/02/2024 11:06,10/02/2024 11:59,0,2.58.72.131,100,3209,1,10/02/2024 11:59,R_2qMNVqZUePoHMD7,NaN,NaN,NaN,NaN,51.5088,-0.093,anonymous,EN,"1,2,3,4,5,6",1,RY303,1,1,2,24,1,Android,39.0,49.0,42.0,59.0,32.0,26.0,29.0,NaN,1,3.80,39.0
19,11/02/2024 20:13,11/02/2024 20:20,0,82.30.148.144,100,458,1,11/02/2024 20:20,R_5sZOANIm8HaOXXn,NaN,NaN,NaN,NaN,53.4003,-2.2154,anonymous,EN,"1,2,3,4,5,6",1,AL554,2,3,3,47,2,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102,1,5.93,NaN

In [24]:
df.columns

Index(['start_date', 'end_date', 'status', 'ip_address', 'progress',
       'duration_seconds', 'finished', 'recorded_date', 'response_id',
       'recipient_last_name', 'recipient_first_name', 'recipient_email',
       'external_reference', 'latitude', 'longitude', 'distribution_channel',
       'user_language', 'consent', 'consent_confirmed', 'participant_id',
       'gender', 'occupation', 'education', 'age', 'phone_checking_frequency',
       'device', 'pickups_mon', 'pickups_tue', 'pickups_wed', 'pickups_thu',
       'pickups_fri', 'pickups_sat', 'pickups_sun', 'ios_pickups', 'q62',
       'maas_score', 'non_ios_avg_pickups'],
      dtype='object')

In [25]:
# Getting rid of columns that are not relevant to the analysis
relevant_columns = ['participant_id',
       'gender', 'occupation', 'education', 'age', 'phone_checking_frequency',
       'device', 'ios_pickups',
       'maas_score', 'non_ios_avg_pickups']

df = df[relevant_columns]
df.head(20)

,participant_id,gender,occupation,education,age,phone_checking_frequency,device,ios_pickups,maas_score,non_ios_avg_pickups
0,Please create your unique identifier code by u...,What gender do you identify as:,Which of the following best describes your emp...,Which of the following best describes your hig...,What is your age?,"Firstly, are you using more than one device?",NaN,6. Find the average number of pick ups for the...,NaN,NaN
1,PA651,2,1,3,34,1,Android,NaN,3.93,49.0
2,Fer01,1,1,1,32,2,Samsung,NaN,2.27,87.0
3,pm492,1,1,6,29,2,Android,NaN,4.80,51.0
4,ML194,2,1,2,29,1,Android,NaN,3.67,93.0
5,FER13,1,2,1,32,1,Samsung,NaN,2.67,97.0
6,KE831,2,4,2,32,2,Android,NaN,3.13,35.0
7,PA741,1,1,3,34,2,Android,NaN,4.20,55.0
8,RI500,2,1,2,46,1,Android,NaN,4.33,94.0
9,PI945,2,6,8,21,2,iPhone,215,2.93,NaN
10,ES663,2,1,2,33,1,Samsung,NaN,4.60,53.0
11,WE718,2,6,6,22,1,iPhone,88,4.00,NaN
12,JO029,2,1,6,43,2,Android,NaN,4.13,42.0
13,AG115,2,4,3,35,2,iPhone,152,2.80,NaN
14,Ja735,1,1,3,39,1,iPhone,179,4.07,NaN
15,ja735,1,1,3,39,1,iPhone,172,4.33,NaN
16,PA741,1,1,3,34,2,Android,NaN,4.00,55.0
17,BA664,2,1,2,33,1,Android,NaN,4.40,57.0
18,RY303,1,1,2,24,1,Android,NaN,3.80,39.0
19,AL554,2,3,3,47,2,iPhone,102,5.93,NaN

In [26]:
# Renaming the phone_checking_frequency column to more_than_one_device 
df.rename(columns={'phone_checking_frequency': 'more_than_one_device'}, inplace=True)
df.head()

,participant_id,gender,occupation,education,age,more_than_one_device,device,ios_pickups,maas_score,non_ios_avg_pickups
0,Please create your unique identifier code by u...,What gender do you identify as:,Which of the following best describes your emp...,Which of the following best describes your hig...,What is your age?,"Firstly, are you using more than one device?",NaN,6. Find the average number of pick ups for the...,NaN,NaN
1,PA651,2,1,3,34,1,Android,NaN,3.93,49.0
2,Fer01,1,1,1,32,2,Samsung,NaN,2.27,87.0
3,pm492,1,1,6,29,2,Android,NaN,4.80,51.0
4,ML194,2,1,2,29,1,Android,NaN,3.67,93.0

### Df Backup

In [27]:
# Creating a backup of the DataFrame before making further changes
df_backup = df.copy()

In [28]:
# Checking the unique values in the more_than_one_device column
print(df['more_than_one_device'].unique())

['Firstly, are you using more than one device?' '1' '2' nan]

In [29]:
# Converting the more_than_one_device column to boolean values
df['more_than_one_device'] = df['more_than_one_device'].astype(object)
df.loc[df['more_than_one_device'] == "1", 'more_than_one_device'] = False
df.loc[df['more_than_one_device'] == "2", 'more_than_one_device'] = True
df.head()

,participant_id,gender,occupation,education,age,more_than_one_device,device,ios_pickups,maas_score,non_ios_avg_pickups
0,Please create your unique identifier code by u...,What gender do you identify as:,Which of the following best describes your emp...,Which of the following best describes your hig...,What is your age?,"Firstly, are you using more than one device?",NaN,6. Find the average number of pick ups for the...,NaN,NaN
1,PA651,2,1,3,34,False,Android,NaN,3.93,49.0
2,Fer01,1,1,1,32,True,Samsung,NaN,2.27,87.0
3,pm492,1,1,6,29,True,Android,NaN,4.80,51.0
4,ML194,2,1,2,29,False,Android,NaN,3.67,93.0

In [30]:
# Converting the gender column to categorical values
df['gender'] = df['gender'].astype(object)
df.loc[df['gender'] == "1", 'gender'] = "Male"
df.loc[df['gender'] == "2", 'gender'] = "Female"
df.head()

,participant_id,gender,occupation,education,age,more_than_one_device,device,ios_pickups,maas_score,non_ios_avg_pickups
0,Please create your unique identifier code by u...,What gender do you identify as:,Which of the following best describes your emp...,Which of the following best describes your hig...,What is your age?,"Firstly, are you using more than one device?",NaN,6. Find the average number of pick ups for the...,NaN,NaN
1,PA651,Female,1,3,34,False,Android,NaN,3.93,49.0
2,Fer01,Male,1,1,32,True,Samsung,NaN,2.27,87.0
3,pm492,Male,1,6,29,True,Android,NaN,4.80,51.0
4,ML194,Female,1,2,29,False,Android,NaN,3.67,93.0

In [31]:
# Dropping the occupation and education
df.drop(columns=['occupation', 'education'], inplace=True)

### Dropped Columns

`occupation` and `education` columns have been dropped. These were originally encoded as numerical values (1–6), but the corresponding labels were not retained, making them uninterpretable for analysis.

In [33]:
df = df.iloc[1:]  # Remove the first row which contains the original column names
df.head(20)

,participant_id,gender,age,more_than_one_device,device,ios_pickups,maas_score,non_ios_avg_pickups
2,Fer01,Male,32,True,Samsung,NaN,2.27,87.0
3,pm492,Male,29,True,Android,NaN,4.80,51.0
4,ML194,Female,29,False,Android,NaN,3.67,93.0
5,FER13,Male,32,False,Samsung,NaN,2.67,97.0
6,KE831,Female,32,True,Android,NaN,3.13,35.0
7,PA741,Male,34,True,Android,NaN,4.20,55.0
8,RI500,Female,46,False,Android,NaN,4.33,94.0
9,PI945,Female,21,True,iPhone,215,2.93,NaN
10,ES663,Female,33,False,Samsung,NaN,4.60,53.0
11,WE718,Female,22,False,iPhone,88,4.00,NaN
12,JO029,Female,43,True,Android,NaN,4.13,42.0
13,AG115,Female,35,True,iPhone,152,2.80,NaN
14,Ja735,Male,39,False,iPhone,179,4.07,NaN
15,ja735,Male,39,False,iPhone,172,4.33,NaN
16,PA741,Male,34,True,Android,NaN,4.00,55.0
17,BA664,Female,33,False,Android,NaN,4.40,57.0
18,RY303,Male,24,False,Android,NaN,3.80,39.0
19,AL554,Female,47,True,iPhone,102,5.93,NaN
20,CH603,Female,42,True,Android,NaN,4.67,23.0
21,AN142,Female,37,True,iPhone,44,3.73,NaN

In [34]:
# Creating a cleaned version of the DataFrame for analysis
qualtrics_cleaned = df.copy()
file_name = "Qualtrics_cleaned.csv"
qualtrics_cleaned.to_csv(os.path.join(OUTPUT_FOLDER_PATH, file_name), index=False)

### Fecthing inhibition scores file

In [35]:
# Loading inhibition scores
inhibition_scores_path = "/Users/remyfernando/Desktop/Noguchi Active/BSc Psychology/Year 3/Research Project/Project data/inhibition_scores.csv"
inhibition_scores_df = pd.read_csv(inhibition_scores_path)
inhibition_scores_df.head()

  participant_id  inhibition_score
0          AT483                45
1          WE718                58
2          AN142                57
3          ES663                53
4          BA664                58

### Joining the two table on participant_id

In [36]:
# Standardize participant IDs to lowercase and strip whitespace
inhibition_scores_df["participant_id"] = inhibition_scores_df["participant_id"].str.lower().str.strip()
qualtrics_cleaned["participant_id"] = qualtrics_cleaned["participant_id"].str.lower().str.strip()

In [37]:
len(inhibition_scores_df), len(qualtrics_cleaned)

(29, 42)

In [38]:
df_merged = inhibition_scores_df.merge(qualtrics_cleaned, on='participant_id', how='inner')
df_merged.head()

,participant_id,inhibition_score,gender,age,more_than_one_device,device,ios_pickups,maas_score,non_ios_avg_pickups
0,at483,45,Female,24,False,iPhone,46,3.27,NaN
1,we718,58,Female,22,False,iPhone,88,4.00,NaN
2,an142,57,Female,37,True,iPhone,44,3.73,NaN
3,es663,53,Female,33,False,Samsung,NaN,4.60,53.0
4,ba664,58,Female,33,False,Android,NaN,4.40,57.0

In [39]:
# Checking for rows where both ios_pickups and non_ios_avg_pickups are not null
df_merged[(df_merged['ios_pickups'].notna()) & (df_merged['non_ios_avg_pickups'].notna())]

Empty DataFrame
Columns: [participant_id, inhibition_score, gender, age, more_than_one_device, device, ios_pickups, maas_score, non_ios_avg_pickups]
Index: []

In [40]:
df_merged.columns
reordered_columns = ['participant_id', 'gender', 'age',
       'more_than_one_device', 'device', 'maas_score', 'ios_pickups',
       'non_ios_avg_pickups', 'inhibition_score']

df_merged = df_merged[reordered_columns]
df_merged.head()

,participant_id,gender,age,more_than_one_device,device,maas_score,ios_pickups,non_ios_avg_pickups,inhibition_score
0,at483,Female,24,False,iPhone,3.27,46,NaN,45
1,we718,Female,22,False,iPhone,4.00,88,NaN,58
2,an142,Female,37,True,iPhone,3.73,44,NaN,57
3,es663,Female,33,False,Samsung,4.60,NaN,53.0,53
4,ba664,Female,33,False,Android,4.40,NaN,57.0,58

In [41]:
df_ready_for_analysis = df_merged.copy()
file_name = "Qualtrics_ready_for_analysis.csv"
df_ready_for_analysis.to_csv(os.path.join(OUTPUT_FOLDER_PATH, file_name), index=False)